### ISSUE TITLE
Edge artefact after align_slice()

### ISSUE THREAD

**Issue by latent-reason** [rg314/pytraction#44]
Samples that undergo large drift cause the PIV measurements to artifacts on the edges. After the drift correction using `align_slice()` the drift is corrected but the PIV thinks this is a displacement.

**Comment by rg314** [comment]
@l-kaplan I've just added the base code to fix this bug. I will implement it in the core package tomorrow. Did you get a chance to look at your data? Let me know if you want to jump on another call.

```
def remove_boarder_from_aligned(aligned_img):
    _,thresh = cv2.threshold(aligned_img,0,255,cv2.THRESH_BINARY)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(9,9))
    res = cv2.morphologyEx(thresh,cv2.MORPH_CLOSE,kernel)
    contours,hierarchy = cv2.findContours(thresh,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cnt = sorted(contours, key=lambda x: cv2.contourArea(x))[0]
    x, y, w, h = cv2.boundingRect(cnt)
    return aligned_img[y:y+h, x:x+h]
```
