### ISSUE TITLE
GoogleDriveDownloader Issue stops TractionForceConfig function from working properly

### ISSUE THREAD

**Issue by jf767** [rg314/pytraction#60]
When trying to run example1.ipynb from the premade examples, calling the TractionForceConfig function causes following error : 

_

> FileNotFoundError                         Traceback (most recent call last)
> Cell In[10], line 1
> ----> 1 traction_config = TractionForceConfig(E=E, scaling_factor=pix_per_um, config=config) # config TractionForceConfig object
>       2 img, ref, _ = traction_config.load_data(img_path, ref_path) # we can load the data using the load_data method
>       4 print(f'The expected shape of the image is {img.shape}')
> 
> File ~/opt/anaconda3/envs/pytraction/lib/python3.8/site-packages/pytraction/core.py:47, in TractionForceConfig.__init__(self, E, scaling_factor, config, min_window_size, meshsize, s, knn, cnn, **kwards)
>      41 self.config = self._config_yaml(
>      42     config, E, min_window_size, s, meshsize, scaling_factor
>      43 )
>      45 self.knn = self._get_knn_model() if knn else None
>      46 self.model, self.pre_fn = (
> ---> 47     self._get_cnn_model(device=self.config["settings"]["device"])
>      48     if cnn
>      49     else (None, None)
>      50 )
>      52 for k, v in kwards:
>      53     self.config[k] = v
> 
> File ~/opt/anaconda3/envs/pytraction/lib/python3.8/site-packages/pytraction/core.py:92, in TractionForceConfig._get_cnn_model(device)
>      83 gdd.download_file_from_google_drive(
>      84     file_id=file_id,
>      85     dest_path=destination,
>    (...)
>      88     overwrite=False,
>      89 )
>      91 # currently using model from 20210316
> ---> 92 best_model = torch.load(f"{tmpdir}/best_model_1.pth", map_location="cpu")
>      93 if device == "cuda" and torch.cuda.is_available():
>      94     best_model = best_model.to("cuda")
> 
> File ~/opt/anaconda3/envs/pytraction/lib/python3.8/site-packages/torch/serialization.py:771, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
>     768 if 'encoding' not in pickle_load_args.keys():
>     769     pickle_load_args['encoding'] = 'utf-8'
> --> 771 with _open_file_like(f, 'rb') as opened_file:
>     772     if _is_zipfile(opened_file):
>     773         # The zipfile reader is going to advance the current file position.
>     774         # If we want to actually tail call to torch.jit.load, we need to
>     775         # reset back to the original position.
>     776         orig_position = opened_file.tell()
> 
> File ~/opt/anaconda3/envs/pytraction/lib/python3.8/site-packages/torch/serialization.py:270, in _open_file_like(name_or_buffer, mode)
>     268 def _open_file_like(name_or_buffer, mode):
>     269     if _is_path(name_or_buffer):
> --> 270         return _open_file(name_or_buffer, mode)
>     271     else:
>     272         if 'w' in mode:
> 
> File ~/opt/anaconda3/envs/pytraction/lib/python3.8/site-packages/torch/serialization.py:251, in _open_file.__init__(self, name, mode)
>     250 def __init__(self, name, mode):
> --> 251     super(_open_file, self).__init__(open(name, mode))
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/jn/khnrf1p13v3g_hq6lnq_gjg80000gn/T/best_model_1.pth'

_

I think that this is another GoogleDriveDownloader error because, in core.py lines 77-81, there is a file called "model.zip" downloaded using GoogleDriveDownloader with the File-ID "1zShYcG8IMsMjB8hA6FcBTIZPfi_wDL4n". That downloads a 0.0B File into the temporary directory again, because of an internal error in the GoogleDriveDownloader module. The missing file "best_model_1.pth" is presumably inside the "model.zip" file, which can't be unzipped because of the flawed download.

Could someone provide the link to these files/their Google Drive as a workaround for that issue?

Thanks in advance!

**Comment by latent-reason** [comment]
Yep same issue. you can construct the file by using the file ID `1zShYcG8IMsMjB8hA6FcBTIZPfi_wDL4n`. 

i.e. `https://drive.google.com/file/d/{FILE_ID}/view?usp=share_link` -> https://drive.google.com/file/d/1zShYcG8IMsMjB8hA6FcBTIZPfi_wDL4n/view?usp=share_link

**Comment by jf767** [comment]
Did not know, that that is possible! 

Thanks for the quick answer!
